-- Applied after Prisma DDL on BOTH hub and cloud. Runtime roles never own tables.
DO $$ BEGIN
 IF NOT EXISTS(SELECT FROM pg_roles WHERE rolname='hotel_app') THEN CREATE ROLE hotel_app NOLOGIN NOSUPERUSER NOBYPASSRLS; END IF;
 IF NOT EXISTS(SELECT FROM pg_roles WHERE rolname='provider_app') THEN CREATE ROLE provider_app NOLOGIN NOSUPERUSER NOBYPASSRLS; END IF;
 IF NOT EXISTS(SELECT FROM pg_roles WHERE rolname='license_agent') THEN CREATE ROLE license_agent NOLOGIN NOSUPERUSER NOBYPASSRLS; END IF;
END $$;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO hotel_app,provider_app,license_agent;
CREATE FUNCTION public.context_tenant() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('app.tenant_id',true),'')::uuid $$;
CREATE FUNCTION public.touch_row() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.id <> OLD.id OR NEW.tenant_id <> OLD.tenant_id OR NEW.created_at <> OLD.created_at OR NEW.created_by IS DISTINCT FROM OLD.created_by THEN RAISE EXCEPTION 'Row identity and provenance are immutable'; END IF;
 NEW.updated_at=greatest(clock_timestamp(),OLD.updated_at+interval '1 microsecond'); RETURN NEW;
END $$;
CREATE FUNCTION public.deny_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Append-only record: create a linked reversal or reprint'; END $$;
CREATE FUNCTION public.deny_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Hard deletes are disabled'; END $$;
CREATE FUNCTION public.require_writable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF current_user='hotel_app' AND current_setting('app.can_write',true) IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'Hotel is read-only'; END IF;
 RETURN NEW;
END $$;
CREATE FUNCTION public.track_change() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE event_id uuid; audit_id uuid; actor uuid; doc jsonb; previous jsonb;
BEGIN
 event_id=nullif(current_setting('app.event_id',true),'')::uuid;
 audit_id=nullif(current_setting('app.audit_id',true),'')::uuid;
 actor=nullif(current_setting('app.user_id',true),'')::uuid;
 IF event_id IS NULL OR audit_id IS NULL THEN RAISE EXCEPTION 'Use an application mutation context'; END IF;
 doc=to_jsonb(NEW); previous=CASE WHEN TG_OP='UPDATE' THEN to_jsonb(OLD) ELSE NULL END;
 IF TG_TABLE_NAME='users' THEN doc=doc-'password_hash'; previous=previous-'password_hash'; END IF;
 IF TG_TABLE_NAME='gateway_credentials' THEN doc=doc-'encrypted_payload'; previous=previous-'encrypted_payload'; END IF;
 IF TG_TABLE_NAME='licenses' THEN doc=doc-'key_hash'; previous=previous-'key_hash'; END IF;
 INSERT INTO public.sync_queue(id,tenant_id,device_id,created_by,table_name,record_id,operation,payload,source_updated_at)
 VALUES(event_id,NEW.tenant_id,NEW.device_id,actor,TG_TABLE_NAME,NEW.id,lower(TG_OP)::"SyncOperation",doc,NEW.updated_at);
 INSERT INTO public.audit_log(id,tenant_id,device_id,created_by,user_id,action,entity,entity_id,before,after,occurred_at)
 VALUES(audit_id,NEW.tenant_id,current_setting('app.device_id',true),actor,actor,
 CASE WHEN TG_OP='UPDATE' AND NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL THEN 'soft_delete' ELSE lower(TG_OP) END,
 TG_TABLE_NAME,NEW.id,previous,doc,clock_timestamp());
 PERFORM set_config('app.event_id','',true); PERFORM set_config('app.audit_id','',true);
 RETURN NEW;
END $$;
ALTER TABLE "tenants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenants" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "tenants" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "tenants" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "tenants" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "tenants" TO hotel_app;
GRANT INSERT ON "tenants" TO provider_app;
CREATE POLICY provider_scope ON "tenants" FOR ALL TO provider_app USING (true) WITH CHECK (true);
GRANT SELECT ON "tenants" TO provider_app;
GRANT UPDATE ON "tenants" TO provider_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "tenants" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "tenants" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "tenants" ADD CONSTRAINT "tenants_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "roles" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "roles" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "roles" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "roles" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "roles" TO hotel_app;
GRANT INSERT ON "roles" TO hotel_app;
GRANT UPDATE ON "roles" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "roles" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "roles" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "roles" ADD CONSTRAINT "roles_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "roles" ADD CONSTRAINT "roles_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "users" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "users" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "users" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "users" TO hotel_app;
GRANT INSERT ON "users" TO hotel_app;
GRANT UPDATE ON "users" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "users" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "users" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "users" ADD CONSTRAINT "users_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "users" ADD CONSTRAINT "users_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "devices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "devices" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "devices" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "devices" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "devices" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "devices" TO hotel_app;
GRANT INSERT ON "devices" TO hotel_app;
GRANT UPDATE ON "devices" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "devices" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "devices" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "devices" ADD CONSTRAINT "devices_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "devices" ADD CONSTRAINT "devices_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "guests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "guests" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "guests" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "guests" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "guests" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "guests" TO hotel_app;
GRANT INSERT ON "guests" TO hotel_app;
GRANT UPDATE ON "guests" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "guests" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "guests" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "guests" ADD CONSTRAINT "guests_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "guests" ADD CONSTRAINT "guests_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "room_types" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "room_types" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "room_types" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "room_types" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "room_types" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "room_types" TO hotel_app;
GRANT INSERT ON "room_types" TO hotel_app;
GRANT UPDATE ON "room_types" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "room_types" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "room_types" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "room_types" ADD CONSTRAINT "room_types_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "room_types" ADD CONSTRAINT "room_types_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "rooms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "rooms" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "rooms" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "rooms" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "rooms" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "rooms" TO hotel_app;
GRANT INSERT ON "rooms" TO hotel_app;
GRANT UPDATE ON "rooms" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "rooms" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "rooms" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "rooms" ADD CONSTRAINT "rooms_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "rooms" ADD CONSTRAINT "rooms_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "rate_plans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "rate_plans" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "rate_plans" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "rate_plans" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "rate_plans" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "rate_plans" TO hotel_app;
GRANT INSERT ON "rate_plans" TO hotel_app;
GRANT UPDATE ON "rate_plans" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "rate_plans" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "rate_plans" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "rate_plans" ADD CONSTRAINT "rate_plans_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "rate_plans" ADD CONSTRAINT "rate_plans_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "reservations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reservations" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "reservations" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "reservations" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "reservations" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "reservations" TO hotel_app;
GRANT INSERT ON "reservations" TO hotel_app;
GRANT UPDATE ON "reservations" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "reservations" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "reservations" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "folios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "folios" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "folios" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "folios" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "folios" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "folios" TO hotel_app;
GRANT INSERT ON "folios" TO hotel_app;
GRANT UPDATE ON "folios" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "folios" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "folios" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "folios" ADD CONSTRAINT "folios_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "folios" ADD CONSTRAINT "folios_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "service_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "service_categories" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "service_categories" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "service_categories" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "service_categories" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "service_categories" TO hotel_app;
GRANT INSERT ON "service_categories" TO hotel_app;
GRANT UPDATE ON "service_categories" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "service_categories" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "service_categories" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "service_categories" ADD CONSTRAINT "service_categories_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "service_categories" ADD CONSTRAINT "service_categories_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "service_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "service_items" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "service_items" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "service_items" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "service_items" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "service_items" TO hotel_app;
GRANT INSERT ON "service_items" TO hotel_app;
GRANT UPDATE ON "service_items" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "service_items" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "service_items" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "service_items" ADD CONSTRAINT "service_items_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "service_items" ADD CONSTRAINT "service_items_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "service_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "service_orders" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "service_orders" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "service_orders" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "service_orders" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "service_orders" TO hotel_app;
GRANT INSERT ON "service_orders" TO hotel_app;
GRANT UPDATE ON "service_orders" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "service_orders" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "service_orders" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "service_orders" ADD CONSTRAINT "service_orders_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "service_orders" ADD CONSTRAINT "service_orders_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "service_order_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "service_order_items" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "service_order_items" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "service_order_items" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "service_order_items" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "service_order_items" TO hotel_app;
GRANT INSERT ON "service_order_items" TO hotel_app;
GRANT UPDATE ON "service_order_items" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "service_order_items" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "service_order_items" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "service_order_items" ADD CONSTRAINT "service_order_items_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "service_order_items" ADD CONSTRAINT "service_order_items_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "folio_charges" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "folio_charges" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "folio_charges" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "folio_charges" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "folio_charges" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "folio_charges" TO hotel_app;
GRANT INSERT ON "folio_charges" TO hotel_app;
CREATE TRIGGER immutable BEFORE UPDATE ON "folio_charges" FOR EACH ROW EXECUTE FUNCTION public.deny_mutation();
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "folio_charges" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "folio_charges" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "folio_charges" ADD CONSTRAINT "folio_charges_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "folio_charges" ADD CONSTRAINT "folio_charges_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payments" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "payments" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "payments" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "payments" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "payments" TO hotel_app;
GRANT INSERT ON "payments" TO hotel_app;
CREATE TRIGGER immutable BEFORE UPDATE ON "payments" FOR EACH ROW EXECUTE FUNCTION public.deny_mutation();
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "payments" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "payments" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "payments" ADD CONSTRAINT "payments_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "payments" ADD CONSTRAINT "payments_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "receipts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "receipts" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "receipts" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "receipts" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "receipts" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "receipts" TO hotel_app;
GRANT INSERT ON "receipts" TO hotel_app;
CREATE TRIGGER immutable BEFORE UPDATE ON "receipts" FOR EACH ROW EXECUTE FUNCTION public.deny_mutation();
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "receipts" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "receipts" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "receipts" ADD CONSTRAINT "receipts_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "receipts" ADD CONSTRAINT "receipts_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "receipt_reprints" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "receipt_reprints" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "receipt_reprints" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "receipt_reprints" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "receipt_reprints" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "receipt_reprints" TO hotel_app;
GRANT INSERT ON "receipt_reprints" TO hotel_app;
CREATE TRIGGER immutable BEFORE UPDATE ON "receipt_reprints" FOR EACH ROW EXECUTE FUNCTION public.deny_mutation();
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "receipt_reprints" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "receipt_reprints" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "receipt_reprints" ADD CONSTRAINT "receipt_reprints_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "receipt_reprints" ADD CONSTRAINT "receipt_reprints_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "receipt_counters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "receipt_counters" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "receipt_counters" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "receipt_counters" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "receipt_counters" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "receipt_counters" TO hotel_app;
GRANT INSERT ON "receipt_counters" TO hotel_app;
GRANT UPDATE ON "receipt_counters" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "receipt_counters" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "receipt_counters" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "receipt_counters" ADD CONSTRAINT "receipt_counters_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "receipt_counters" ADD CONSTRAINT "receipt_counters_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "shifts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "shifts" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "shifts" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "shifts" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "shifts" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "shifts" TO hotel_app;
GRANT INSERT ON "shifts" TO hotel_app;
GRANT UPDATE ON "shifts" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "shifts" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "shifts" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "shifts" ADD CONSTRAINT "shifts_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "shifts" ADD CONSTRAINT "shifts_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "housekeeping_tasks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "housekeeping_tasks" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "housekeeping_tasks" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "housekeeping_tasks" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "housekeeping_tasks" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "housekeeping_tasks" TO hotel_app;
GRANT INSERT ON "housekeeping_tasks" TO hotel_app;
GRANT UPDATE ON "housekeeping_tasks" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "housekeeping_tasks" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "housekeeping_tasks" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "housekeeping_tasks" ADD CONSTRAINT "housekeeping_tasks_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "housekeeping_tasks" ADD CONSTRAINT "housekeeping_tasks_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventory_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "inventory_items" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "inventory_items" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "inventory_items" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "inventory_items" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "inventory_items" TO hotel_app;
GRANT INSERT ON "inventory_items" TO hotel_app;
GRANT UPDATE ON "inventory_items" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "inventory_items" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "inventory_items" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "inventory_items" ADD CONSTRAINT "inventory_items_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "inventory_items" ADD CONSTRAINT "inventory_items_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventory_movements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "inventory_movements" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "inventory_movements" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "inventory_movements" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "inventory_movements" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "inventory_movements" TO hotel_app;
GRANT INSERT ON "inventory_movements" TO hotel_app;
CREATE TRIGGER immutable BEFORE UPDATE ON "inventory_movements" FOR EACH ROW EXECUTE FUNCTION public.deny_mutation();
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "inventory_movements" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "inventory_movements" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "inventory_movements" ADD CONSTRAINT "inventory_movements_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "inventory_movements" ADD CONSTRAINT "inventory_movements_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "online_bookings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "online_bookings" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "online_bookings" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "online_bookings" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "online_bookings" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "online_bookings" TO hotel_app;
GRANT INSERT ON "online_bookings" TO hotel_app;
GRANT UPDATE ON "online_bookings" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "online_bookings" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "online_bookings" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "online_bookings" ADD CONSTRAINT "online_bookings_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "online_bookings" ADD CONSTRAINT "online_bookings_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "payment_transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payment_transactions" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "payment_transactions" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "payment_transactions" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "payment_transactions" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "payment_transactions" TO hotel_app;
GRANT INSERT ON "payment_transactions" TO hotel_app;
GRANT UPDATE ON "payment_transactions" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "payment_transactions" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "payment_transactions" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "payment_transactions" ADD CONSTRAINT "payment_transactions_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "payment_transactions" ADD CONSTRAINT "payment_transactions_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "audit_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_log" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "audit_log" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "audit_log" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "audit_log" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "audit_log" TO hotel_app;
GRANT INSERT ON "audit_log" TO hotel_app;
GRANT INSERT ON "audit_log" TO provider_app;
CREATE POLICY provider_scope ON "audit_log" FOR ALL TO provider_app USING (true) WITH CHECK (true);
CREATE TRIGGER immutable BEFORE UPDATE ON "audit_log" FOR EACH ROW EXECUTE FUNCTION public.deny_mutation();
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sync_queue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sync_queue" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "sync_queue" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "sync_queue" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "sync_queue" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "sync_queue" TO hotel_app;
GRANT INSERT ON "sync_queue" TO hotel_app;
GRANT UPDATE ON "sync_queue" TO hotel_app;
GRANT INSERT ON "sync_queue" TO provider_app;
CREATE POLICY provider_scope ON "sync_queue" FOR ALL TO provider_app USING (true) WITH CHECK (true);
GRANT UPDATE ON "sync_queue" TO provider_app;
ALTER TABLE "sync_queue" ADD CONSTRAINT "sync_queue_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "sync_queue" ADD CONSTRAINT "sync_queue_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sync_metadata" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sync_metadata" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "sync_metadata" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "sync_metadata" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "sync_metadata" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "sync_metadata" TO hotel_app;
ALTER TABLE "sync_metadata" ADD CONSTRAINT "sync_metadata_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "sync_metadata" ADD CONSTRAINT "sync_metadata_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "settings" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "settings" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "settings" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "settings" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "settings" TO hotel_app;
GRANT INSERT ON "settings" TO hotel_app;
GRANT UPDATE ON "settings" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "settings" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "settings" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "settings" ADD CONSTRAINT "settings_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "settings" ADD CONSTRAINT "settings_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "refresh_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "refresh_sessions" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "refresh_sessions" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "refresh_sessions" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "refresh_sessions" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "refresh_sessions" TO hotel_app;
GRANT INSERT ON "refresh_sessions" TO hotel_app;
GRANT UPDATE ON "refresh_sessions" TO hotel_app;
ALTER TABLE "refresh_sessions" ADD CONSTRAINT "refresh_sessions_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "refresh_sessions" ADD CONSTRAINT "refresh_sessions_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "gateway_credentials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "gateway_credentials" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "gateway_credentials" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "gateway_credentials" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "gateway_credentials" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "gateway_credentials" TO hotel_app;
GRANT INSERT ON "gateway_credentials" TO hotel_app;
GRANT UPDATE ON "gateway_credentials" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "gateway_credentials" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "gateway_credentials" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "gateway_credentials" ADD CONSTRAINT "gateway_credentials_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "gateway_credentials" ADD CONSTRAINT "gateway_credentials_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "license_cache" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "license_cache" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "license_cache" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "license_cache" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "license_cache" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "license_cache" TO hotel_app;
ALTER TABLE "license_cache" ADD CONSTRAINT "license_cache_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "license_cache" ADD CONSTRAINT "license_cache_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscriptions" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "subscriptions" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "subscriptions" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "subscriptions" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT INSERT ON "subscriptions" TO provider_app;
CREATE POLICY provider_scope ON "subscriptions" FOR ALL TO provider_app USING (true) WITH CHECK (true);
GRANT SELECT ON "subscriptions" TO provider_app;
GRANT UPDATE ON "subscriptions" TO provider_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "subscriptions" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "subscriptions" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "licenses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "licenses" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "licenses" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "licenses" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "licenses" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT INSERT ON "licenses" TO provider_app;
CREATE POLICY provider_scope ON "licenses" FOR ALL TO provider_app USING (true) WITH CHECK (true);
GRANT SELECT ON "licenses" TO provider_app;
GRANT UPDATE ON "licenses" TO provider_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "licenses" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "licenses" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "licenses" ADD CONSTRAINT "licenses_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "licenses" ADD CONSTRAINT "licenses_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_billing" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscription_billing" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "subscription_billing" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "subscription_billing" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "subscription_billing" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT INSERT ON "subscription_billing" TO provider_app;
CREATE POLICY provider_scope ON "subscription_billing" FOR ALL TO provider_app USING (true) WITH CHECK (true);
GRANT SELECT ON "subscription_billing" TO provider_app;
CREATE TRIGGER immutable BEFORE UPDATE ON "subscription_billing" FOR EACH ROW EXECUTE FUNCTION public.deny_mutation();
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "subscription_billing" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "subscription_billing" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "subscription_billing" ADD CONSTRAINT "subscription_billing_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "subscription_billing" ADD CONSTRAINT "subscription_billing_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "hub_heartbeats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hub_heartbeats" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "hub_heartbeats" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "hub_heartbeats" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "hub_heartbeats" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT INSERT ON "hub_heartbeats" TO provider_app;
CREATE POLICY provider_scope ON "hub_heartbeats" FOR ALL TO provider_app USING (true) WITH CHECK (true);
GRANT SELECT ON "hub_heartbeats" TO provider_app;
GRANT UPDATE ON "hub_heartbeats" TO provider_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "hub_heartbeats" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "hub_heartbeats" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "hub_heartbeats" ADD CONSTRAINT "hub_heartbeats_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "hub_heartbeats" ADD CONSTRAINT "hub_heartbeats_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "notifications" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "notifications" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "notifications" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "notifications" TO hotel_app;
GRANT INSERT ON "notifications" TO hotel_app;
GRANT UPDATE ON "notifications" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "notifications" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "notifications" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "draft_submissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "draft_submissions" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "draft_submissions" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "draft_submissions" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "draft_submissions" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT SELECT ON "draft_submissions" TO hotel_app;
GRANT INSERT ON "draft_submissions" TO hotel_app;
GRANT UPDATE ON "draft_submissions" TO hotel_app;
CREATE TRIGGER writable BEFORE INSERT OR UPDATE ON "draft_submissions" FOR EACH ROW EXECUTE FUNCTION public.require_writable();
CREATE TRIGGER outbox AFTER INSERT OR UPDATE ON "draft_submissions" FOR EACH ROW EXECUTE FUNCTION public.track_change();
ALTER TABLE "draft_submissions" ADD CONSTRAINT "draft_submissions_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "draft_submissions" ADD CONSTRAINT "draft_submissions_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "provider_audit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "provider_audit" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON "provider_audit" FOR ALL TO hotel_app,license_agent USING (tenant_id=public.context_tenant()) WITH CHECK (tenant_id=public.context_tenant());
CREATE TRIGGER no_delete BEFORE DELETE ON "provider_audit" FOR EACH ROW EXECUTE FUNCTION public.deny_delete();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON "provider_audit" FOR EACH ROW EXECUTE FUNCTION public.touch_row();
GRANT INSERT ON "provider_audit" TO provider_app;
CREATE POLICY provider_scope ON "provider_audit" FOR ALL TO provider_app USING (true) WITH CHECK (true);
GRANT SELECT ON "provider_audit" TO provider_app;
CREATE TRIGGER immutable BEFORE UPDATE ON "provider_audit" FOR EACH ROW EXECUTE FUNCTION public.deny_mutation();
ALTER TABLE "provider_audit" ADD CONSTRAINT "provider_audit_tenant_fk" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE "provider_audit" ADD CONSTRAINT "provider_audit_creator_fk" FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
GRANT SELECT,INSERT,UPDATE ON license_cache TO license_agent;
ALTER TABLE tenants ADD CONSTRAINT tenant_identity CHECK (id=tenant_id);
ALTER TABLE reservations ADD CONSTRAINT stay_dates CHECK(check_out_date>check_in_date), ADD CONSTRAINT guest_counts CHECK(adults>0 AND children>=0), ADD CONSTRAINT nonnegative_rate CHECK(rate>=0);
ALTER TABLE room_types ADD CONSTRAINT capacity_positive CHECK(capacity>0 AND online_allotment>=0 AND base_rate>=0);
ALTER TABLE rate_plans ADD CONSTRAINT rate_dates CHECK(valid_to>=valid_from AND rate>=0);
ALTER TABLE service_categories ADD CONSTRAINT valid_tax CHECK(vat_rate BETWEEN 0 AND 100 AND service_charge_rate BETWEEN 0 AND 100);
ALTER TABLE service_items ADD CONSTRAINT item_price CHECK(price>=0 AND inventory_qty_per_unit>0);
ALTER TABLE service_order_items ADD CONSTRAINT item_quantity CHECK(quantity>0 AND unit_price>=0 AND subtotal>=0);
ALTER TABLE payments ADD CONSTRAINT payment_parent CHECK(num_nonnulls(folio_id,order_id)=1), ADD CONSTRAINT payment_sign CHECK((reversal_of_id IS NULL AND amount>0) OR (reversal_of_id IS NOT NULL AND amount<0));
ALTER TABLE receipts ADD CONSTRAINT receipt_parent CHECK(num_nonnulls(folio_id,order_id)=1);
ALTER TABLE folio_charges ADD CONSTRAINT nonzero_charge CHECK(amount<>0);
ALTER TABLE subscriptions ADD CONSTRAINT positive_limits CHECK(max_devices>0 AND max_rooms>0);
CREATE UNIQUE INDEX payment_single_reversal ON payments(tenant_id,reversal_of_id) WHERE reversal_of_id IS NOT NULL;
CREATE UNIQUE INDEX charge_single_reversal ON folio_charges(tenant_id,reversal_of_id) WHERE reversal_of_id IS NOT NULL;
CREATE UNIQUE INDEX receipt_single_reversal ON receipts(tenant_id,reversal_of_id) WHERE reversal_of_id IS NOT NULL;
-- No direct Supabase Data API access. Hosted apps will call authenticated cloud APIs.
DO $$ DECLARE r text; BEGIN
 FOREACH r IN ARRAY ARRAY['anon','authenticated','service_role'] LOOP
  IF EXISTS(SELECT FROM pg_roles WHERE rolname=r) THEN
   EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I',r);
   EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM %I',r);
  END IF;
 END LOOP;
END $$;
